#!/usr/bin/env python3
"""
Batch 2: appends additional curated concept questions + a small calc top-up,
then rebuilds ids and rewrites content/questions.json to reach the 300 target.
Run AFTER build_bank.py:  python3 content/bank_batch2.py
"""
import json, random, os
random.seed(7)
HERE = os.path.dirname(__file__); TODAY = "2026-07-08"
FED="Federal Laws"; STATE="Uniform State"; GEN="General Mortgage Knowledge"
ORIG="Origination Activities"; ETH="Ethics"
B=[]
def q(a,r,s,d,t,stem,o,ci,e,c): B.append({"content_area":a,"outline_ref":r,"subtopic":s,"difficulty":d,"type":t,"stem":stem,"options":o,"correct_index":ci,"explanation":e,"primary_source_citation":c,"last_reviewed_date":TODAY})

# ---------- FEDERAL (depth) ----------
q(FED,"1.1.3","RESPA prohibited","medium","application-scenario","An MLO wants to require borrowers to use a specific title company the MLO owns. Under RESPA this is:",["Always permitted","Prohibited as required use, absent limited exceptions and proper ABA disclosure","Required by law","Permitted if cheaper"],1,"RESPA generally bars requiring the use of a particular provider ('required use'). Referrals to an affiliate are allowed only with an Affiliated Business Arrangement disclosure and without requiring use, except for limited attorney/title exceptions.","12 U.S.C. \u00a72608; 12 CFR \u00a71024.15")
q(FED,"1.1.5","RESPA application info","medium","recall","Under Regulation X, information collected on a mortgage application is used to:",["Set the federal funds rate","Evaluate the borrower and produce required disclosures","Publish borrower names","Determine the appraiser"],1,"Application information supports evaluating the borrower and generating required disclosures (Loan Estimate, etc.). RESPA/Reg X governs the settlement-cost disclosures that flow from the application.","Regulation X, 12 CFR \u00a71024")
q(FED,"1.1.6","RESPA loss mitigation","hard","application-scenario","Under RESPA servicing rules, before making the first foreclosure filing a servicer generally must:",["File immediately upon one missed payment","Wait until the borrower is more than 120 days delinquent","Obtain a new appraisal","Raise the interest rate"],1,"RESPA generally prohibits a servicer from making the first notice or filing for foreclosure until the borrower is more than 120 days delinquent, giving time to pursue loss-mitigation options.","Regulation X, 12 CFR \u00a71024.41(f)")
q(FED,"1.2.3","ECOA denial basis","medium","application-scenario","Which is a permissible reason to deny a mortgage application under ECOA?",["The applicant is unmarried","Insufficient income to support the requested payment","The applicant receives Social Security","The applicant's national origin"],1,"Denials must rest on legitimate creditworthiness factors such as insufficient income, excessive DTI, or poor credit. Marital status, receipt of protected income, and national origin are prohibited bases.","Regulation B, 12 CFR \u00a71002.6")
q(FED,"1.2.4","Regulation B scope","easy","recall","Regulation B implements which federal law?",["RESPA","TILA","ECOA","HMDA"],2,"Regulation B implements the Equal Credit Opportunity Act (ECOA). Reg X = RESPA, Reg Z = TILA, Reg C = HMDA.","12 CFR Part 1002")
q(FED,"1.2.5","ECOA notice timing","medium","recall","ECOA requires notification of action taken on a completed application within:",["3 days","10 days","30 days","90 days"],2,"A creditor must notify the applicant of action taken (approval, counteroffer, adverse action, or incompleteness) within 30 days of receiving a completed application.","Regulation B, 12 CFR \u00a71002.9(a)(1)")
q(FED,"1.2.11","ECOA income consideration","medium","application-scenario","Under ECOA, part-time income the applicant relies on:",["Must be ignored","Must be considered and may not be discounted solely because it is part-time","Disqualifies the applicant","Requires a co-signer"],1,"A creditor may not automatically discount or exclude income because it is part-time, from public assistance, or from protected sources; it must be considered to the extent it is likely to continue.","Regulation B, 12 CFR \u00a71002.6(b)(5)")
q(FED,"1.2.12","ECOA creditworthiness","medium","recall","Which factor is a legitimate creditworthiness consideration under ECOA?",["Religion","Marital status in a non-community-property context","The applicant's credit history and payment record","Whether the applicant has children"],2,"Credit history and payment record are legitimate. ECOA prohibits reliance on religion, childbearing, and (except in limited community-property situations) marital status.","Regulation B, 12 CFR \u00a71002.6")
q(FED,"1.2.7","Adverse action example","medium","application-scenario","Which is an 'adverse action' requiring an ECOA notice?",["Approving the loan as applied for","A counteroffer the applicant accepts","Denying the requested credit","Providing the Loan Estimate"],2,"Adverse action includes a denial or a revocation of credit, or an unfavorable change in terms. Approval as requested and an accepted counteroffer are not adverse action; a denial is.","Regulation B, 12 CFR \u00a71002.2(c)")
q(FED,"1.3.2","TILA coverage","medium","application-scenario","TILA generally applies to a loan that is:",["A business loan to an LLC","Consumer credit secured by a dwelling","An agricultural loan","A commercial construction loan"],1,"TILA applies to consumer credit, including consumer loans secured by a dwelling. Business, commercial, and agricultural credit are generally exempt.","Regulation Z, 12 CFR \u00a71026.3")
q(FED,"1.3.3","Finance charge","medium","recall","Under TILA, the 'finance charge' is:",["The loan principal","The cost of consumer credit as a dollar amount, including interest and certain fees","The down payment","The property tax"],1,"The finance charge is the total dollar cost of credit to the consumer, including interest and certain fees imposed as a condition of the loan. It feeds the APR calculation.","Regulation Z, 12 CFR \u00a71026.4")
q(FED,"1.4.2","TRID loans covered","medium","application-scenario","TRID's Loan Estimate/Closing Disclosure requirements generally apply to:",["Home-equity lines of credit","Most closed-end consumer mortgages secured by real property","Reverse mortgages","Business loans"],1,"TRID applies to most closed-end consumer credit transactions secured by real property. HELOCs, reverse mortgages, and certain other loans use different disclosures and are excluded.","Regulation Z, 12 CFR \u00a71026.19(e),(f)")
q(FED,"1.4.3","LE contents","medium","recall","The Loan Estimate discloses all of the following EXCEPT:",["Estimated interest rate and monthly payment","Estimated closing costs and cash to close","The borrower's credit score value","Whether the rate can increase"],2,"The Loan Estimate discloses the rate, payment, closing costs, cash to close, and features like whether the rate or balance can increase. It does not print the borrower's credit score.","Regulation Z, 12 CFR \u00a71026.37")
q(FED,"1.4.6","CD contents","medium","recall","The Closing Disclosure differs from the Loan Estimate in that it shows:",["Only estimates","The actual, final loan terms and closing costs","No fees","The appraiser's opinion"],1,"The Closing Disclosure presents the final, actual terms and costs, allowing the borrower to compare against the earlier Loan Estimate. It must be received at least three business days before consummation.","Regulation Z, 12 CFR \u00a71026.38")
q(FED,"1.4.7","Business day rule","hard","application-scenario","For the Closing Disclosure's three-business-day rule, 'business day' counts:",["Only Monday-Friday excluding all holidays for delivery timing under the specific (all-but-Sundays/holidays) definition","All calendar days","Only days the lender is open, for both LE and CD equally","Weekdays only, never Saturdays"],0,"TRID uses a 'specific' business-day definition (all calendar days except Sundays and federal holidays) for the CD waiting period and rescission, and a 'general' definition (days the creditor is open) for other timing like LE delivery. Saturdays generally count under the specific rule.","Regulation Z, 12 CFR \u00a71026.2(a)(6)")
q(FED,"1.4.8","Incomplete TRID","medium","application-scenario","If a required TRID disclosure contains an error affecting a fee, the creditor generally must:",["Ignore it","Provide a corrected disclosure and, if a tolerance is exceeded, cure it (refund) within the required period","Cancel the loan","Charge the borrower a fee"],1,"When a disclosure error causes a tolerance violation, the creditor must correct the disclosure and cure the overcharge by refunding the excess to the borrower, generally within 60 days of consummation.","Regulation Z, 12 CFR \u00a71026.19(f)(2)")
q(FED,"1.4.10","Info on request","medium","recall","Upon a consumer's request, a creditor must generally provide:",["The lender's tax returns","The specific reasons a particular charge or term was set, per applicable rules","Other borrowers' files","Nothing"],1,"Consumers are entitled to certain information on request, such as the basis for adverse action reasons (ECOA) and copies of appraisals/valuations (ECOA valuations rule). Creditors must respond as the applicable rule requires.","Regulation B, 12 CFR \u00a71002.9, \u00a71002.14")
q(FED,"1.4.11","Rescission on refinance","medium","application-scenario","A refinance with the SAME creditor on a principal dwelling is rescindable:",["For the entire loan amount","Only to the extent new money exceeds the existing balance plus refinance costs","Never","Only if over $100,000"],1,"When refinancing with the same creditor, rescission generally applies only to the 'new money' portion, the amount financed that exceeds the unpaid balance, earned finance charges, and refinancing costs, not the entire loan.","Regulation Z, 12 CFR \u00a71026.23(f)(2)")
q(FED,"1.5.8","USA PATRIOT Act","medium","recall","The USA PATRIOT Act's Customer Identification Program requires institutions to:",["Deny all foreign applicants","Verify the identity of customers opening accounts","Report all loans to the FBI","Provide free credit reports"],1,"The Act's CIP requirements obligate financial institutions to verify the identity of persons opening accounts and to maintain records, supporting anti-terrorism and anti-money-laundering efforts.","31 U.S.C. \u00a75318(l)")
q(FED,"1.6.2","HUD role","easy","recall","HUD's role in mortgage lending includes:",["Setting the federal funds rate","Administering FHA insurance programs and fair-housing enforcement","Licensing MLOs directly","Buying loans on the secondary market"],1,"HUD administers FHA mortgage insurance and enforces the Fair Housing Act. It wrote the original SAFE Act regulations before authority transferred to the CFPB; it does not set monetary policy or buy loans (the GSEs do).","42 U.S.C. \u00a73608; National Housing Act")
q(FED,"1.3.4","Rescission notice copies","medium","recall","For a rescindable loan, the creditor must give each consumer with the right to rescind:",["One copy of the notice","Two copies of the notice of the right to rescind","No notice","A verbal explanation only"],1,"Each consumer entitled to rescind must receive two copies of the written notice of the right to rescind (one to keep, one to exercise the right), plus the material disclosures.","Regulation Z, 12 CFR \u00a71026.23(b)")
q(FED,"1.1.1","Mortgage broker definition","easy","recall","Under RESPA, a 'mortgage broker' is generally:",["The title insurer","A person who brings a borrower and lender together but does not fund the loan","The appraiser","The county recorder"],1,"A mortgage broker arranges or negotiates a loan between borrower and lender for compensation but typically does not use its own funds to make the loan. RESPA governs its fees and referral arrangements.","Regulation X, 12 CFR \u00a71024.2")
q(FED,"1.3.6","HPML appraisal","hard","application-scenario","For a higher-priced mortgage loan, the appraisal rules generally require:",["No appraisal","A written appraisal with a physical interior inspection by a licensed appraiser","A drive-by only","The MLO's own estimate"],1,"HPML rules require a written appraisal based on a physical, interior property inspection by a certified or licensed appraiser, with a free copy to the borrower, and a second appraisal in certain flipping situations.","Regulation Z, 12 CFR \u00a71026.35(c)")
q(FED,"1.5.5","Do-Not-Call","medium","application-scenario","An MLO cold-calls a consumer on the National Do-Not-Call Registry with no prior relationship. This is:",["Always fine","Generally prohibited without an established business relationship or consent","Required marketing","Only an issue after 5 calls"],1,"Telemarketing to numbers on the Do-Not-Call Registry generally requires prior express consent or an established business relationship. Violations carry penalties under the TSR/TCPA framework.","16 CFR Part 310 (Telemarketing Sales Rule)")

# ---------- ETHICS (depth) ----------
q(ETH,"5.1.1","Permitted duties","medium","application-scenario","Which is a permitted duty for an MLO?",["Inflating the appraised value","Accurately completing the application from borrower-provided, verified information","Splitting unearned fees","Coaching a borrower to hide debt"],1,"Accurately preparing the application from verified, borrower-provided information is a core permitted duty. Inflating value, splitting unearned fees, and coaching concealment are prohibited.","SAFE Act prohibited/permitted acts, 12 CFR \u00a71008.103")
q(ETH,"5.1.1","Compensation ethics","medium","application-scenario","An MLO is offered a bonus by a lender to place borrowers in loans with higher rates. Accepting it would:",["Be fine if disclosed","Violate the LO compensation rule barring pay based on loan terms","Be required","Be ethical if the borrower agrees"],1,"Compensation may not be based on a transaction's terms such as the interest rate. A bonus tied to placing borrowers in higher-rate loans is prohibited and incentivizes steering.","Regulation Z, 12 CFR \u00a71026.36(d)")
q(ETH,"5.1.2","Coercion of appraiser","medium","application-scenario","Telling an appraiser 'we need at least $X to make this deal work' is:",["Acceptable guidance","Prohibited coercion violating appraiser independence","Required disclosure","A permitted factual input"],1,"Communicating a target or minimum value to influence the appraiser is prohibited coercion. Only factual, non-value-suggestive information may be shared.","Regulation Z, 12 CFR \u00a71026.42")
q(ETH,"5.1.2","Fair lending","medium","application-scenario","Offering less favorable terms to an applicant because of their national origin is:",["Permissible risk-based pricing","Illegal discrimination under fair-lending laws","Required by investors","Acceptable if disclosed"],1,"Varying terms based on a protected characteristic like national origin is illegal disparate treatment under ECOA and the Fair Housing Act. Pricing must reflect legitimate risk factors only.","ECOA 15 U.S.C. \u00a71691; FHA 42 U.S.C. \u00a73605")
q(ETH,"5.1.3","Asset fraud","medium","application-scenario","A borrower's bank statement shows a large deposit two days before application, matching the exact down payment. The MLO should:",["Ignore it","Source and document the deposit; unexplained funds are a red flag","Delete the statement","Tell the borrower to move the money"],1,"Large, recently-deposited funds that conveniently cover the down payment are a fraud red flag (possible undisclosed loan). They must be sourced and documented, not ignored or concealed.","Fraud red-flag guidance; ATR verification")
q(ETH,"5.1.3","Employment fraud","medium","application-scenario","A borrower asks the MLO to accept a 'verification of employment' from a friend posing as an employer. The MLO should:",["Accept it to help the borrower","Refuse; verifications must come from legitimate, independent sources","Accept it if notarized","Split the difference"],1,"A fabricated VOE is fraud. Employment and income verification must come from legitimate, independent sources. Knowingly accepting a fake verification exposes the MLO to criminal and licensing consequences.","Fraud prohibitions; SAFE Act prohibited acts")
q(ETH,"5.1.3","Contract red flag","medium","application-scenario","The sales contract shows a large 'seller credit' plus a side agreement for cash back to the buyer not disclosed to the lender. This is:",["Standard practice","Undisclosed and likely mortgage fraud that must be disclosed to the lender","A permitted incentive","The seller's business only"],1,"Undisclosed cash-back or side agreements distort the true transaction and value, constituting mortgage fraud. All terms affecting the transaction must be disclosed to the lender.","Fraud prohibitions; accurate disclosure duty")
q(ETH,"5.1.4","Suspicious activity","medium","application-scenario","An MLO reasonably suspects a transaction involves identity theft. The MLO should:",["Warn the suspect","Follow the institution's procedures, which may include a SAR, without tipping off the subject","Do nothing","Post about it online"],1,"Suspected fraud/identity theft should be handled through the institution's compliance procedures, which may include filing a SAR, and the subject must not be tipped off. Public disclosure would be improper.","BSA/AML; 31 U.S.C. \u00a75318(g)")
q(ETH,"5.1.4","Info to borrower","medium","application-scenario","A borrower asks the MLO whether to lie about occupancy to get a better rate. The MLO should:",["Explain how to do it convincingly","Refuse and explain that the application must be truthful","Do it for them","Charge extra for the advice"],1,"The MLO must not assist misrepresentation. Occupancy must be stated truthfully; advising or helping a borrower lie is facilitating fraud.","SAFE Act prohibited acts; fraud prohibitions")
q(ETH,"5.1.5","UDAAP","medium","application-scenario","Advertising a 'fixed payment' for a loan whose payment can actually increase is:",["Acceptable puffery","A deceptive act (UDAAP) and prohibited","Required disclosure","Fine if in small print"],1,"Describing a loan in a way that misleads consumers about a material term (like payment stability) is a deceptive act under UDAAP and the advertising rules, regardless of fine print.","Dodd-Frank UDAAP, 12 U.S.C. \u00a75531; Reg N")
q(ETH,"5.1.6","Predatory lending","medium","application-scenario","Repeatedly refinancing a borrower to generate fees with little benefit to the borrower is:",["Good customer service","Loan flipping, a predatory practice","Required by HOEPA","Permitted if disclosed"],1,"Loan flipping, refinancing repeatedly to strip equity and generate fees without net benefit to the borrower, is a predatory practice restricted under HOEPA and prohibited by fair-dealing standards.","HOEPA, 15 U.S.C. \u00a71639; 12 CFR \u00a71026.34")
q(ETH,"5.2.1","Permitted fees","medium","application-scenario","An MLO may ethically charge a borrower:",["A fee for a referral to a title company","Bona fide fees for services actually performed, properly disclosed","A duplicate of a third-party fee for extra profit","An undisclosed markup"],1,"Only bona fide, disclosed fees for services actually rendered are permissible. Referral fees, undisclosed markups, and duplicating third-party charges for profit violate RESPA and fair-dealing rules.","12 U.S.C. \u00a72607; disclosure rules")
q(ETH,"5.2.1","Fee changes","medium","application-scenario","After locking, the MLO wants to raise a lender fee that was in the zero-tolerance bucket with no changed circumstance. This is:",["Permitted","Not permitted; zero-tolerance fees cannot increase absent a valid changed circumstance","Required","Fine if the borrower agrees"],1,"Zero-tolerance charges (like lender fees) cannot increase from the Loan Estimate without a valid changed circumstance; increasing them otherwise triggers a required cure. Borrower 'agreement' does not override the tolerance rule.","Regulation Z, 12 CFR \u00a71026.19(e)(3)")
q(ETH,"5.2.3","Material info discovery","medium","application-scenario","An MLO discovers the property has an undisclosed second structure being used commercially. The MLO should:",["Ignore it","Convey the material information to the lender/underwriter","Hide it to close faster","Tell only the borrower"],1,"Material facts about the property and its use affect value and eligibility and must be conveyed to the lender/underwriter. Concealing them to close the loan is improper.","Duty of accurate disclosure to lender")
q(ETH,"5.2.4","Conflict of interest","medium","application-scenario","An MLO is originating a loan for a property they personally intend to purchase from the borrower. The MLO should:",["Proceed quietly","Disclose the conflict of interest to all parties as required","Hide the relationship","Inflate the value"],1,"A personal interest in the transaction is a conflict that must be disclosed to the relevant parties. Undisclosed self-dealing undermines the integrity of the transaction.","Ethical standards; fair-dealing duty")
q(ETH,"5.2.4","POA scenario","medium","application-scenario","A borrower's relative insists on signing loan documents under a power of attorney the lender has not approved. The MLO should:",["Allow it to be helpful","Require a valid, lender-approved POA before anyone signs for the borrower","Sign for the borrower","Ignore the requirement"],1,"Signing for a borrower requires a valid POA acceptable to the lender and title company. Proceeding without approval risks an unenforceable transaction and potential fraud.","Standard settlement practice; state POA law")
q(ETH,"5.2.4","Credit report permissible purpose","medium","application-scenario","Pulling a consumer's credit report without a permissible purpose is:",["Fine for marketing","A FCRA violation","Required for all inquiries","Acceptable with a verbal ok only sometimes"],1,"The FCRA permits pulling a consumer report only for a permissible purpose, such as a credit transaction the consumer initiated. Pulling reports without one (e.g., for marketing) violates the FCRA.","FCRA, 15 U.S.C. \u00a71681b")
q(ETH,"5.2.2","Complaint handling","medium","application-scenario","The best ethical practice when a borrower complains about a fee is to:",["Dismiss the complaint","Review it in good faith, explain or correct as warranted, and document the response","Cancel the loan","Blame the borrower"],1,"Complaints should be handled in good faith: investigate, explain or correct legitimate issues, and document the resolution. This aligns with servicer error-resolution duties and ethical practice.","Regulation X error resolution, 12 CFR \u00a71024.35")
q(ETH,"5.1.1","Dual tracking","hard","application-scenario","A servicer proceeds with foreclosure while a complete loss-mitigation application is pending review. This 'dual tracking' is:",["Encouraged","Generally prohibited under RESPA servicing rules","Required","Permitted after 30 days"],1,"RESPA servicing rules restrict dual tracking: once a complete loss-mitigation application is received in time, the servicer generally may not make the first foreclosure filing or proceed to sale while it is under review.","Regulation X, 12 CFR \u00a71024.41")

# ---------- GENERAL (depth) ----------
q(GEN,"3.1.1","QM presumption","hard","application-scenario","A prime (non-higher-priced) qualified mortgage receives:",["No presumption","A conclusive (safe harbor) presumption of ATR compliance","A rebuttable presumption only","An automatic denial"],1,"Prime QMs that are not higher-priced receive a conclusive presumption (safe harbor) of ATR compliance. Higher-priced QMs receive only a rebuttable presumption.","Regulation Z, 12 CFR \u00a71026.43(e)(1)")
q(GEN,"3.1.1","QM points and fees","medium","recall","For a QM, points and fees generally may not exceed:",["1% of the loan","3% of the loan amount (for larger loans)","5% of the loan","10% of the loan"],1,"For a general QM on a larger loan, points and fees generally may not exceed 3% of the total loan amount, with higher percentage caps for smaller loan amounts.","Regulation Z, 12 CFR \u00a71026.43(e)(3)")
q(GEN,"3.1.4","Alt-A","medium","recall","An 'Alt-A' loan generally describes:",["A government loan","A loan between prime and subprime, often with reduced documentation","A reverse mortgage","A construction loan"],1,"Alt-A loans fall between prime and subprime in risk, historically featuring reduced documentation or other flexibilities for otherwise creditworthy borrowers. They are non-conforming and carry added risk.","Industry classification")
q(GEN,"3.2.2","ARM index","medium","recall","In an ARM, the 'index' is:",["The lender's profit margin","A published benchmark rate the loan is tied to (e.g., SOFR)","A fixed number","The borrower's credit score"],1,"The index is an independent, published benchmark (such as SOFR) that moves with the market. Adding the fixed margin to the index yields the fully indexed rate at adjustment.","ARM disclosures, 12 CFR \u00a71026.20(c)")
q(GEN,"3.2.2","ARM margin","easy","recall","The margin on an ARM:",["Changes at every adjustment","Is the fixed amount added to the index and stays constant for the loan's life","Equals the index","Is set by the borrower"],1,"The margin is the lender's fixed spread added to the index; it remains constant for the life of the loan while the index fluctuates.","ARM disclosures, 12 CFR \u00a71026.20(c)")
q(GEN,"3.3.1","Escrow account","easy","recall","A mortgage escrow (impound) account is used to:",["Hold the down payment","Collect and pay property taxes and insurance","Store the appraisal","Pay the MLO"],1,"An escrow account collects a portion of taxes and insurance with each payment so the servicer can pay those bills when due, spreading the cost over the year.","Regulation X, 12 CFR \u00a71024.17")
q(GEN,"3.3.1","Lien priority","medium","recall","Lien priority generally determines:",["The interest rate","The order in which creditors are paid in a foreclosure","The appraisal method","The loan term"],1,"Lien priority (typically by recording order, 'first in time, first in right') sets the order creditors are paid from foreclosure proceeds. A first mortgage is paid before subordinate liens.","Property law; recording statutes")
q(GEN,"3.3.2","Yield spread premium","hard","recall","A yield spread premium historically referred to:",["A borrower discount","Compensation to a broker for delivering a higher-rate loan","A government subsidy","An escrow surplus"],1,"A yield spread premium was compensation paid to a broker for originating a loan at a higher rate than the borrower might otherwise qualify for. The LO compensation rule now restricts pay based on loan terms, curbing this.","Regulation Z, 12 CFR \u00a71026.36(d)")
q(GEN,"3.3.2","Lender credit","medium","recall","A lender credit on the Closing Disclosure:",["Increases the borrower's costs","Offsets closing costs, usually in exchange for a higher interest rate","Is the down payment","Is a penalty"],1,"A lender credit reduces the borrower's closing costs, typically in exchange for a higher interest rate (the inverse of paying points). It must be disclosed and generally cannot be reduced later.","Regulation Z, 12 CFR \u00a71026.19(e)")
q(GEN,"3.3.4","APR vs note rate","medium","application-scenario","Two loans have the same note rate, but Loan A has higher fees. Loan A's APR will be:",["Lower than Loan B","Higher than Loan B","Identical to Loan B","Zero"],1,"Because the APR incorporates certain fees in addition to interest, the loan with higher fees (Loan A) will show a higher APR even at the same note rate. This helps borrowers compare true cost.","Regulation Z, 12 CFR \u00a71026.22")
q(GEN,"3.3.4","Subordination","medium","recall","A subordination agreement:",["Pays off a loan","Changes lien priority so one lien agrees to rank behind another","Increases the rate","Cancels the mortgage"],1,"A subordination agreement changes the normal priority so an existing lien (e.g., a HELOC) agrees to remain behind a new first mortgage, commonly used when refinancing a first lien while keeping a second.","Property law; recording practice")
q(GEN,"3.1.2","GSE role","medium","recall","Fannie Mae and Freddie Mac primarily:",["Originate loans directly to consumers","Purchase conforming loans and provide liquidity to lenders","Insure FHA loans","License MLOs"],1,"The GSEs buy conforming loans from lenders on the secondary market and securitize them, providing liquidity so lenders can originate new loans. They do not lend directly to consumers.","GSE charters; secondary-market structure")
q(GEN,"3.2.2","Conversion option","medium","recall","A 'convertible' ARM allows the borrower to:",["Convert to a different property","Convert the ARM to a fixed rate under stated conditions","Skip payments","Remove the margin"],1,"A convertible ARM gives the borrower an option to convert to a fixed-rate loan during a specified window, usually for a fee, providing a hedge against rising rates.","Product feature; ARM disclosures")

# ---------- ORIGINATION (depth) ----------
q(ORIG,"4.1.2","Permissible questions","medium","application-scenario","During application, which question is impermissible?",["What is your gross monthly income?","Do you plan to have children?","What are your monthly debts?","Is this your primary residence?"],1,"Asking about childbearing plans is prohibited under ECOA. Income, debts, and occupancy are legitimate, necessary application questions.","Regulation B, 12 CFR \u00a71002.5(d)")
q(ORIG,"4.1.3","Authorization to verify","medium","recall","Before verifying a borrower's bank and employment records, the MLO should obtain:",["Nothing","The borrower's signed authorization","The seller's permission","A court order"],1,"The borrower's signed authorization permits the lender to verify employment, income, assets, and pull credit. Verifications support the ability-to-repay determination.","Standard underwriting; FCRA permissible purpose")
q(ORIG,"4.1.6","Early disclosures","medium","recall","The Loan Estimate and the special information booklet are examples of:",["Closing documents","Early disclosures due shortly after application","Servicing notices","Marketing materials"],1,"Early disclosures (Loan Estimate, special information booklet, homeownership counseling list) are provided shortly after application to inform the consumer before they commit.","Regulation Z \u00a71026.19(e); Regulation X \u00a71024.20")
q(ORIG,"4.1.6","Affiliated business","medium","application-scenario","When referring to an affiliated provider, the MLO must give the borrower:",["A gift","An Affiliated Business Arrangement disclosure","A rate reduction","Cash"],1,"An ABA disclosure informing the borrower of the affiliate relationship and estimated charges is required, and use of the affiliate generally may not be required.","Regulation X, 12 CFR \u00a71024.15")
q(ORIG,"4.2.1","Credit report use","medium","application-scenario","In borrower analysis, the credit report is used to:",["Set the property value","Assess creditworthiness and existing debts","Choose the title company","Determine the appraiser"],1,"The credit report reveals payment history, outstanding debts, and derogatory items, informing creditworthiness and the DTI calculation, key inputs to the credit decision.","Standard underwriting; ATR credit history factor")
q(ORIG,"4.2.1","Residual income","medium","recall","'Residual income' in underwriting refers to:",["Income left after paying major monthly obligations","The lender's profit","The down payment","The escrow balance"],0,"Residual income is the money remaining after major monthly obligations (including the mortgage) are paid, used notably in VA underwriting and as an ATR alternative to DTI to gauge repayment capacity.","VA underwriting; ATR 12 CFR \u00a71026.43(c)")
q(ORIG,"4.2.2","Appraisal timing","medium","application-scenario","On most first-lien loans, the borrower must receive a copy of the appraisal:",["Never","Promptly upon completion or at least 3 business days before consummation","Only at closing","Only if they pass"],1,"Under the ECOA valuations rule, the creditor must provide copies of appraisals and other written valuations promptly upon completion or at least three business days before consummation, whichever is earlier.","Regulation B, 12 CFR \u00a71002.14")
q(ORIG,"4.2.4","Hazard insurance","easy","recall","Hazard (homeowner's) insurance is required to:",["Protect the lender's and owner's interest in the property against loss","Pay the down payment","Cover the appraisal","Guarantee the rate"],0,"Lenders require hazard insurance to protect the property (collateral) against fire and similar losses, safeguarding both the owner's and the lender's interest. It is typically escrowed.","Standard lending requirement")
q(ORIG,"4.3.1","Title insurance","medium","recall","A lender's title insurance policy protects:",["The borrower's equity","The lender against covered title defects up to the loan amount","The appraiser","The seller"],1,"A lender's (loan) policy protects the lender against covered title defects, typically decreasing with the loan balance. An owner's policy separately protects the buyer's equity.","Standard settlement practice")
q(ORIG,"4.3.3","Origination fee","medium","recall","An origination fee is:",["A third-party recording cost","A charge by the lender/broker for processing the loan","Prepaid interest","Property tax"],1,"An origination fee compensates the lender or broker for taking, processing, and underwriting the loan. It is a lender charge in the zero-tolerance category under TRID.","Regulation Z \u00a71026.37; TRID tolerances")
q(ORIG,"4.3.4","Closing documents","medium","recall","A key document signed at closing that creates the borrower's promise to repay is the:",["Deed of trust only","Promissory note","Appraisal","Title commitment"],1,"The promissory note is the borrower's written promise to repay the debt on stated terms. The mortgage or deed of trust separately pledges the property as security for that note.","Standard closing documents")
q(ORIG,"4.1.7","Intent to proceed","medium","application-scenario","A creditor may NOT impose fees on a consumer before:",["Delivering the Closing Disclosure","The consumer receives the Loan Estimate and indicates intent to proceed (except a bona fide credit report fee)","The appraisal","Funding"],1,"Except for a bona fide and reasonable credit report fee, a creditor may not charge the consumer any fee until the consumer has received the Loan Estimate and communicated intent to proceed.","Regulation Z, 12 CFR \u00a71026.19(e)(2)")
q(ORIG,"4.2.3","Preliminary title timing","medium","recall","The title search/commitment is typically ordered:",["After closing","Early in processing so title issues can be cleared before closing","Only if the borrower asks","Never"],1,"Title work is ordered early in processing so that liens, judgments, or other clouds on title can be identified and resolved before the closing date.","Standard settlement workflow")

# ---------- STATE (depth) ----------
q(STATE,"2.1.2","Public record filing","medium","recall","Which document is typically filed in the public record to give notice of the lender's lien?",["The promissory note","The mortgage or deed of trust","The Loan Estimate","The appraisal"],1,"The mortgage or deed of trust is recorded in the public land records to perfect and give notice of the lender's security interest. The note itself is generally not recorded.","Recording statutes; state law")
q(STATE,"2.2.1","Regulator powers","medium","recall","A state mortgage regulator generally may NOT:",["Examine licensees","Issue and revoke licenses","Exceed the authority granted by statute","Investigate complaints"],2,"Regulators may license, examine, investigate, and discipline, but they may not exceed the authority the legislature delegated to them; acting beyond that authority is a common basis for challenging regulatory action.","12 U.S.C. \u00a75111; State Model Law")
q(STATE,"2.2.2","NMLS registry","easy","recall","The NMLS serves as:",["A lender that funds loans","The system of record for licensing and registration of MLOs across states","A credit bureau","An appraisal firm"],1,"The Nationwide Multistate Licensing System is the system of record through which MLOs are licensed/registered and through which states coordinate supervision. Consumer Access lets the public verify originators.","12 U.S.C. \u00a75101 et seq.")
q(STATE,"2.2.5","Dual compensation","hard","application-scenario","Under the LO compensation rule, an originator generally may not:",["Be paid a salary","Receive compensation from both the consumer and another person on the same transaction","Be paid per loan","Earn a commission"],1,"The rule prohibits dual compensation, an originator receiving pay from both the consumer and another party (like the creditor) on the same transaction. Salary, per-loan, and permissible commissions are allowed.","Regulation Z, 12 CFR \u00a71026.36(d)(2)")
q(STATE,"2.3.2","Licensed services","medium","recall","A licensed MLO is authorized to:",["Perform appraisals","Take applications and offer or negotiate residential mortgage loan terms","Issue title insurance","Practice law"],1,"An MLO license authorizes taking applications and offering/negotiating residential mortgage terms. Appraising, title insurance, and legal practice require separate credentials.","12 U.S.C. \u00a75102(4)")
q(STATE,"2.3.4","Entities needing MLO","medium","application-scenario","A nondepository mortgage company that originates residential loans must:",["Employ or contract licensed MLOs and hold the required company license","Operate without any license","Use only registered (depository) MLOs","Hold only a real estate license"],0,"Nondepository lenders and brokers must hold the required state company license and ensure their originators are licensed MLOs under Regulation H. Depository registration (Reg G) is a separate regime.","12 CFR Part 1008 (Reg H)")
q(STATE,"2.3.7","Retake waiting period","medium","recall","After failing the SAFE MLO test, a candidate must wait how long before the next attempt (first through third fails)?",["24 hours","30 days","6 months","1 year"],1,"After each of the first three failures, a candidate must wait 30 days before retaking. After three consecutive failures, the wait is 180 days.","NMLS Testing Handbook, test retake policy")
q(STATE,"2.3.8","Sponsorship","medium","application-scenario","An MLO's license is generally not active to originate until:",["They pass the test","They are sponsored by a licensed employer in NMLS","They complete CE","They post a bond"],1,"Even with an approved license, an MLO typically cannot originate until an employer sponsors them through NMLS, linking the individual license to the licensed company.","NMLS sponsorship requirement; state law")
q(STATE,"2.3.9","MLO definition","easy","recall","Under the SAFE Act, a mortgage loan originator is someone who, for compensation:",["Only processes paperwork","Takes a residential mortgage application AND offers or negotiates terms","Appraises property","Records deeds"],1,"An MLO both takes a residential mortgage loan application and offers or negotiates terms of a residential mortgage loan for compensation or gain. Doing only one, or purely clerical work, generally does not meet the definition.","12 U.S.C. \u00a75102(4)")
q(STATE,"2.3.10","License denial grounds","medium","recall","A state may deny an MLO license for:",["Having any debt","A disqualifying criminal history or failure to demonstrate financial responsibility/character","Being a first-time applicant","Working part-time"],1,"Grounds for denial include disqualifying criminal history, failure to meet financial-responsibility or character-and-fitness standards, or providing false information, not simply having debt or being new.","12 U.S.C. \u00a75104")
q(STATE,"2.3.12","Change of employment","medium","application-scenario","When a licensed MLO changes employers, they must:",["Retake the SAFE test","Update their NMLS record and obtain new sponsorship","Get a new SSN","Redo pre-licensing education"],1,"A change of employer requires updating the NMLS record and obtaining sponsorship by the new employer; the license and test do not need to be redone for the move.","NMLS transition requirements")
q(STATE,"2.4.5","Permissible act","medium","application-scenario","Which is a permissible act for a licensed MLO?",["Using a borrower's info without authorization","Disclosing their NMLS ID and providing accurate disclosures","Steering for higher pay","Splitting unearned fees"],1,"Providing the NMLS identifier and accurate, required disclosures is permissible and expected. Unauthorized use of borrower information, steering, and unearned-fee splitting are prohibited.","12 CFR \u00a71008.107; RESPA/Reg Z")
q(STATE,"2.4.6","Penalties","medium","recall","Failure to comply with state mortgage law may result in:",["A thank-you letter","Fines, license suspension or revocation, and other enforcement action","Automatic license renewal","A higher commission"],1,"Noncompliance can lead to civil penalties, license suspension or revocation, cease-and-desist orders, and restitution, depending on the violation and state law.","State Model Law enforcement provisions")

# calc top-up (monthly payment via factor, plus a few more)
def money(n): return "${:,.0f}".format(n)
def money2(n): return "${:,.2f}".format(n)
def mc(correct, distractors, fmt):
    import random as _r
    opts=[correct]+distractors; _r.shuffle(opts); return [fmt(o) for o in opts], opts.index(correct)
# simple down-payment-percent-from-dollars
for _ in range(5):
    price=random.choice([250000,300000,320000,360000,400000]); dpd=random.choice([25000,30000,40000,50000,60000])
    correct=round(dpd/price*100,1)
    opts,ci=mc(correct,[round(correct*1.2,1),round(correct*0.8,1),round(100-correct,1)],lambda o:f"{o}%")
    B.append({"content_area":ORIG,"outline_ref":"4.4.3","subtopic":"Calculations - down payment %","difficulty":"easy","type":"calculation",
      "stem":f"A buyer pays {money(dpd)} down on a {money(price)} home. What down-payment percentage is that?","options":opts,"correct_index":ci,
      "explanation":f"Down payment % = down / price = {money(dpd)} / {money(price)} = {correct}%.","primary_source_citation":"Standard purchase calculation","last_reviewed_date":TODAY})
# monthly interest portion (first month)
for _ in range(5):
    loan=random.choice([200000,250000,300000,325000,360000]); rate=random.choice([0.05,0.055,0.06,0.065,0.07])
    correct=round(loan*rate/12,2)
    opts,ci=mc(correct,[round(correct*1.1,2),round(correct*0.9,2),round(loan*rate/360,2)],money2)
    B.append({"content_area":ORIG,"outline_ref":"4.4.1","subtopic":"Calculations - monthly interest","difficulty":"medium","type":"calculation",
      "stem":f"On a {money(loan)} loan at {rate*100:.2f}%, how much of the first monthly payment is interest?","options":opts,"correct_index":ci,
      "explanation":f"First-month interest = balance x rate / 12 = {money(loan)} x {rate:.4f} / 12 = {money2(correct)}.","primary_source_citation":"Standard amortization","last_reviewed_date":TODAY})

# ---- merge + re-id ----
data=json.load(open(os.path.join(HERE,"questions.json")))
allq=data["questions"]+B
order={FED:1,STATE:2,GEN:3,ORIG:4,ETH:5}
allq.sort(key=lambda x:(order[x["content_area"]],x["outline_ref"]))
for i,q_ in enumerate(allq,1): q_["id"]=f"Q{i:04d}"
data["questions"]=allq; data["meta"]["total"]=len(allq); data["meta"]["version"]="0.4"
json.dump(data,open(os.path.join(HERE,"questions.json"),"w"),indent=2,ensure_ascii=False)
print(f"Batch 2 added {len(B)} questions. New total: {len(allq)}")
