#!/usr/bin/env python3
"""
Batch 3: final gap-fill to reach the 300 target.
Run AFTER bank_batch2.py:  python3 content/bank_batch3.py
Targets: Federal +12, General +17, Ethics +12, State +2 = 43 -> total 300.
"""
import json, os
HERE = os.path.dirname(__file__); TODAY = "2026-07-08"
FED="Federal Laws"; STATE="Uniform State"; GEN="General Mortgage Knowledge"
ORIG="Origination Activities"; ETH="Ethics"
B=[]
def q(a,r,s,d,t,stem,o,ci,e,c): B.append({"content_area":a,"outline_ref":r,"subtopic":s,"difficulty":d,"type":t,"stem":stem,"options":o,"correct_index":ci,"explanation":e,"primary_source_citation":c,"last_reviewed_date":TODAY})

# ---------- FEDERAL (+12) ----------
q(FED,"1.3.4","Rescission mechanics","hard","application-scenario","A borrower validly rescinds a refinance. Within how long must the creditor return money and release its security interest?",["3 days","20 calendar days","60 days","1 year"],1,"After a valid rescission, the creditor generally has 20 calendar days to return any money or property and reflect that the security interest is void. The borrower then tenders back loan proceeds.","Regulation Z, 12 CFR \u00a71026.23(d)")
q(FED,"1.4.7","APR re-disclosure trigger","hard","application-scenario","A corrected Closing Disclosure and a new three-day waiting period are generally triggered when:",["Any fee changes by $1","The APR becomes inaccurate beyond tolerance, a prepayment penalty is added, or the loan product changes","The appraisal is late","The borrower changes address"],1,"Only three changes restart the three-business-day CD clock: an APR that exceeds the accuracy tolerance, addition of a prepayment penalty, or a change in the loan product. Most other changes require a corrected CD but no new waiting period.","Regulation Z, 12 CFR \u00a71026.19(f)(2)(ii)")
q(FED,"1.5.2","Risk-based pricing notice","medium","application-scenario","A lender approves a borrower at a higher rate than its best customers based on the credit report. The FCRA generally requires:",["No notice","A risk-based pricing notice (or a credit score disclosure exception notice)","A denial letter","A new appraisal"],1,"When a consumer receives materially less favorable terms based on a credit report, the FCRA risk-based pricing rule requires a notice, often satisfied by providing a credit score disclosure exception notice to all applicants.","FCRA; 12 CFR Part 1022 Subpart H")
q(FED,"1.5.2","FACTA disposal rule","medium","recall","The FACTA Disposal Rule requires businesses to:",["Keep all consumer reports forever","Properly dispose of consumer report information to prevent unauthorized access","Email reports to consumers","Publish reports"],1,"The Disposal Rule requires reasonable measures (like shredding or wiping) to dispose of consumer report information so it cannot be reconstructed, protecting consumers from identity theft.","FACTA; 16 CFR Part 682")
q(FED,"1.1.3","RESPA one-day advance","medium","application-scenario","Charging a borrower a fee for preparing the Closing Disclosure or TILA disclosures is:",["Permitted","Prohibited; a lender may not charge a fee specifically for preparing required disclosures","Required","Capped at $50"],1,"RESPA prohibits charging a fee specifically for preparing the statutorily required disclosures (Closing Disclosure, escrow statements, TILA disclosures). Legitimate origination fees for services are separate.","Regulation X, 12 CFR \u00a71024.12")
q(FED,"1.2.7","Adverse action with score","medium","recall","When adverse action is based on a credit score, the notice must include:",["The lender's profit","The credit score, range, and key factors that adversely affected it","Other applicants' scores","Nothing extra"],1,"If a credit score was used in taking adverse action, the FCRA requires the notice to include the score, the range of possible scores, and the key factors that adversely affected it, along with the credit bureau's details.","FCRA, 15 U.S.C. \u00a71681m(a)")
q(FED,"1.5.10","SCRA protections","medium","application-scenario","Under the Servicemembers Civil Relief Act, a pre-service mortgage's interest rate during active duty is generally capped at:",["No cap","6%","10%","18%"],1,"The SCRA caps the interest rate on obligations incurred before active duty at 6% during the period of military service, upon proper request, and provides foreclosure protections for servicemembers.","50 U.S.C. \u00a73937 (SCRA)")
q(FED,"1.3.3","Amount financed","medium","recall","Under TILA, the 'amount financed' is:",["The total of payments","The loan amount provided to the borrower, less prepaid finance charges","The property value","The down payment"],1,"The amount financed is the credit extended to the borrower, calculated as the principal minus prepaid finance charges. It differs from the total of payments, which includes all interest over the term.","Regulation Z, 12 CFR \u00a71026.18(b)")
q(FED,"1.1.7","Escrow shortage","medium","application-scenario","An annual escrow analysis reveals a shortage. RESPA generally allows the servicer to:",["Demand full repayment immediately with no options","Offer the borrower the option to repay the shortage over at least 12 months (for smaller shortages)","Cancel the loan","Ignore it"],1,"For an escrow shortage, RESPA generally requires the servicer to allow repayment of smaller shortages over a period of at least 12 months, rather than demanding an immediate lump sum.","Regulation X, 12 CFR \u00a71024.17(f)")
q(FED,"1.6.1","CFPB enforcement","medium","recall","The CFPB enforces consumer financial law primarily through:",["Setting mortgage rates","Supervision, examinations, and enforcement actions against violators","Issuing appraisals","Approving individual loans"],1,"The CFPB supervises covered institutions, conducts examinations, and brings enforcement actions (including restitution and penalties) for violations of federal consumer financial law.","12 U.S.C. \u00a75563, \u00a75564")
q(FED,"1.4.9","Changed circumstance timing","hard","recall","After a valid changed circumstance, a revised Loan Estimate must generally be delivered within:",["24 hours","3 business days of receiving information establishing the change","30 days","At closing"],1,"A revised Loan Estimate reflecting a changed circumstance must generally be provided within three business days of receiving the information sufficient to establish the change, and cannot be issued on or after the Closing Disclosure is provided.","Regulation Z, 12 CFR \u00a71026.19(e)(4)")
q(FED,"1.2.9","Government monitoring info","medium","application-scenario","For a face-to-face application where the borrower declines to provide demographic information, the MLO must:",["Deny the application","Note the information based on visual observation or surname","Skip the section entirely","Guess and record it as borrower-provided"],1,"Government monitoring information supports fair-lending oversight. If the applicant declines during an in-person application, the MLO must note ethnicity, race, and sex based on visual observation or surname, and mark that the applicant declined.","Regulation C, 12 CFR \u00a71003.4; Regulation B \u00a71002.13")

# ---------- GENERAL (+17) ----------
q(GEN,"3.3.3","Discount point effect","medium","recall","Paying discount points generally:",["Raises the interest rate","Lowers the interest rate in exchange for an upfront cost","Has no effect on rate","Eliminates PMI"],1,"Discount points are prepaid interest paid at closing to buy down (lower) the note rate. The borrower trades an upfront cost for a lower rate and payment over time.","Regulation Z \u00a71026.4; standard pricing")
q(GEN,"3.3.3","2-1 buydown","medium","application-scenario","In a 2-1 temporary buydown, the interest rate is:",["Permanently reduced by 2%","Reduced by 2% in year one and 1% in year two, then reverts to the note rate","Increased over time","Fixed for 30 years at the buydown rate"],1,"A 2-1 buydown temporarily lowers the rate 2% below the note rate in year one and 1% below in year two, then the full note rate applies. Funds to cover the difference are typically escrowed upfront.","Product structure; disclosed under Regulation Z")
q(GEN,"3.3.3","PITI","easy","recall","'PITI' stands for:",["Principal, interest, taxes, and insurance","Points, interest, title, and inspection","Principal, income, term, interest","Payment, insurance, tax, index"],0,"PITI is the full monthly housing payment: principal, interest, taxes, and insurance. It is the basis for the front-end (housing) qualifying ratio.","Standard underwriting term")
q(GEN,"3.3.4","Prepayment penalty","medium","application-scenario","A prepayment penalty charges the borrower for:",["Making a late payment","Paying off the loan early","Missing escrow","Refinancing with the same lender only"],1,"A prepayment penalty is a fee for paying the loan off (or paying it down substantially) before a set time. QM and HOEPA rules sharply limit or prohibit prepayment penalties on covered loans.","Regulation Z \u00a71026.43(g); \u00a71026.32")
q(GEN,"3.1.3","FHA/VA assumability","medium","application-scenario","Compared with most conventional loans, FHA and VA loans are more likely to be:",["Non-assumable","Assumable by a qualified buyer","Interest-only","Balloon loans"],1,"Government loans (FHA/VA) are generally assumable by a qualified buyer, whereas most conventional loans contain due-on-sale clauses preventing assumption. Assumption can be attractive when rates have risen.","Product features; 12 U.S.C. \u00a71701j-3 exceptions")
q(GEN,"3.3.4","Mortgage vs deed of trust","medium","recall","The main difference between a mortgage and a deed of trust is:",["The interest rate","A deed of trust involves a third-party trustee and often allows non-judicial foreclosure","The loan amount","One is federal, one is state"],1,"A mortgage is a two-party security instrument; a deed of trust adds a neutral trustee who holds title in trust and can conduct a non-judicial foreclosure where state law permits. Both secure the note.","State property law")
q(GEN,"3.3.4","Judicial vs non-judicial","medium","recall","Non-judicial foreclosure generally:",["Requires a court lawsuit","Proceeds through a power-of-sale clause without court action, where state law allows","Is illegal","Applies only to FHA loans"],1,"Non-judicial foreclosure uses a power-of-sale clause (typically in a deed of trust) to foreclose without a court case, where permitted by state law; judicial foreclosure requires a lawsuit. Availability varies by state.","State foreclosure law")
q(GEN,"3.2.2","Teaser rate","medium","recall","An ARM 'teaser' (initial) rate is:",["The fully indexed rate","A low introductory rate below the fully indexed rate for an initial period","The lifetime cap","The margin"],1,"The teaser is a discounted introductory rate below the fully indexed rate. When it expires, the rate adjusts toward index plus margin, potentially causing payment shock, which ATR underwriting must account for.","ARM disclosures; ATR 12 CFR \u00a71026.43")
q(GEN,"3.1.1","QM term limit","medium","recall","A qualified mortgage may not have a loan term exceeding:",["15 years","20 years","30 years","40 years"],2,"A QM's term may not exceed 30 years. Terms beyond 30 years, along with interest-only, negative amortization, and balloon features, disqualify a loan from general QM status.","Regulation Z, 12 CFR \u00a71026.43(e)(2)")
q(GEN,"3.2.5","Reverse mortgage repayment","medium","application-scenario","A HECM reverse mortgage generally becomes due when:",["The borrower makes a late payment","The borrower dies, sells, or permanently moves out","The rate adjusts","Five years pass"],1,"A HECM becomes due and payable when the last borrower dies, sells the home, or permanently moves out, or fails to meet obligations like paying taxes and insurance. There are no required monthly P&I payments during occupancy.","HECM rules, 24 CFR Part 206")
q(GEN,"3.2.6","HELOC draw period","medium","recall","During a HELOC's draw period, the borrower typically:",["Cannot access funds","May borrow up to the credit limit and often pays interest-only","Must repay in full monthly","Pays no interest"],1,"In the draw period a HELOC borrower can advance funds up to the limit, frequently with interest-only payments; the repayment period follows, when principal and interest are amortized, often causing payment increases.","Open-end credit, 12 CFR \u00a71026.40")
q(GEN,"3.1.4","Subprime borrower","medium","recall","A subprime loan generally serves borrowers with:",["Excellent credit only","Weaker credit profiles, typically at higher rates to offset risk","No income","Government guarantees"],1,"Subprime loans serve borrowers with impaired or limited credit and carry higher rates/fees reflecting greater default risk. They are non-conforming and receive extra regulatory scrutiny.","Interagency subprime guidance")
q(GEN,"3.3.1","Tolerance vs rate lock","medium","application-scenario","A borrower locks the rate but closing is delayed past the lock expiration. Typically:",["The rate stays locked forever","The lock may expire, requiring re-lock at current market or an extension fee","The loan is void","The lender must pay the borrower"],1,"A rate lock guarantees terms only for its stated period. If closing slips past expiration, the borrower may need to re-lock at prevailing rates or pay an extension fee, depending on the lender's policy.","Standard lock practice")
q(GEN,"3.2.1","Amortization","easy","recall","In a fully amortizing fixed-rate loan, over time each payment applies:",["More to interest, never to principal","Increasingly more to principal and less to interest","Only to escrow","Only to principal"],1,"With level payments, early payments are mostly interest; as the balance declines, a growing share goes to principal. By maturity the loan is paid in full (fully amortized).","Standard amortization")
q(GEN,"3.3.2","Servicing definition","easy","recall","Loan 'servicing' refers to:",["Originating the loan","Collecting payments and managing escrow, statements, and payoff","Appraising the property","Selling the home"],1,"Servicing is the ongoing administration of the loan after closing: collecting payments, managing escrow, sending statements, and handling payoff and default. Servicing can be sold separately from the loan.","12 U.S.C. \u00a72605")
q(GEN,"3.1.2","Conforming limit purpose","medium","recall","The FHFA conforming loan limit determines:",["The maximum interest rate","The largest loan the GSEs will purchase as conforming","The minimum down payment","The appraisal fee"],1,"The conforming loan limit sets the maximum loan size eligible for GSE purchase as conforming; loans above it are jumbo (non-conforming). Limits are set annually and vary by area.","FHFA conforming loan limits")
q(GEN,"3.3.4","Conveyance","easy","recall","'Conveyance' in real estate refers to:",["The transfer of title/ownership from one party to another","The loan payment","The appraisal","The escrow deposit"],0,"Conveyance is the transfer of title or an interest in real property from one party to another, typically by deed. It is central to closing a purchase transaction.","Property law")

# ---------- ETHICS (+12) ----------
q(ETH,"5.1.1","Marketing services agreement","hard","application-scenario","A title company pays an MLO a monthly 'marketing fee' far above the value of any marketing actually done, tied to referrals. This is:",["Permissible marketing","A disguised kickback that likely violates RESPA","Required advertising","Acceptable if in a contract"],1,"Payments dressed up as marketing but actually compensating referrals, or exceeding fair market value for services performed, are disguised kickbacks under RESPA. A written agreement does not legitimize an unlawful referral payment.","12 U.S.C. \u00a72607; CFPB MSA guidance")
q(ETH,"5.1.2","Elder financial exploitation","medium","application-scenario","An elderly borrower seems confused and is being pressured by a relative into a cash-out refinance that benefits the relative. The MLO should:",["Close quickly","Be alert to elder financial exploitation and not proceed with a transaction that appears coerced or unsuitable","Ignore the dynamic","Increase the loan amount"],1,"Signs of coercion or diminished capacity in an elderly borrower are red flags for financial exploitation. The MLO should not facilitate a coerced or unsuitable transaction and should follow escalation procedures.","Elder financial abuse guidance; suitability duty")
q(ETH,"5.1.2","Referral fee to agent","medium","application-scenario","An MLO offers a real estate agent $500 per closed loan referred. This is:",["Permissible networking","A prohibited referral fee under RESPA","Required co-marketing","Fine if the borrower is told"],1,"Paying a real estate agent for loan referrals is a prohibited RESPA Section 8 referral fee. Co-marketing is permitted only if each party pays fair market value for their share and no payment is for referrals.","12 U.S.C. \u00a72607(a)")
q(ETH,"5.1.3","Non-arm's-length","medium","application-scenario","In a sale between family members (non-arm's-length), the MLO should:",["Treat it as a standard sale with no extra scrutiny","Disclose the relationship to the lender and apply any additional program requirements","Hide the relationship","Inflate the value to help"],1,"Non-arm's-length (identity-of-interest) transactions carry higher fraud risk and often trigger additional lender requirements. The relationship must be disclosed and program rules applied, not concealed.","Agency guidelines; disclosure duty")
q(ETH,"5.1.4","Verifying application info","medium","application-scenario","The MLO's ethical duty regarding application information is to:",["Accept everything at face value","Take reasonable steps to verify accuracy and resolve discrepancies","Alter figures to help approval","Only verify income"],1,"MLOs should take reasonable steps to verify the accuracy of application information and resolve red flags or discrepancies. Blindly accepting or altering information breaches the duty of integrity.","SAFE Act prohibited acts; underwriting standards")
q(ETH,"5.1.5","Trigger terms","medium","application-scenario","An ad states 'only 3% down!' Under advertising rules, stating certain trigger terms requires:",["Nothing further","Disclosure of additional required terms (e.g., APR and other conditions)","A guarantee of approval","The borrower's credit score"],1,"Advertising specific credit terms (trigger terms) requires disclosure of other required terms so the ad is not misleading, consistent with TILA advertising rules and Regulation N.","Regulation Z, 12 CFR \u00a71026.24; Reg N")
q(ETH,"5.2.1","Closing cost scenario","medium","application-scenario","At closing, the borrower's fees are higher than the Loan Estimate with no valid changed circumstance, exceeding tolerance. The MLO/lender must:",["Keep the extra","Cure the tolerance violation by refunding the excess to the borrower","Charge more","Cancel the loan"],1,"When fees exceed the good-faith tolerance without a valid changed circumstance, the creditor must cure by refunding the overage to the borrower (generally within 60 days of consummation).","Regulation Z, 12 CFR \u00a71026.19(f)(2)")
q(ETH,"5.2.3","Info from employers","medium","application-scenario","An employer verifying employment volunteers that the borrower is about to be laid off. The MLO should:",["Ignore it","Treat this as material information affecting repayment and convey it to the underwriter","Hide it to close","Tell only the borrower"],1,"Impending loss of employment is material to the ability to repay and must be conveyed to the underwriter. Concealing known adverse changes in the borrower's situation is improper.","Duty of accurate disclosure; ATR")
q(ETH,"5.2.4","Unexplained deposit","medium","application-scenario","A borrower's account shows a large deposit they cannot explain. The MLO should:",["Count it toward assets without question","Require documentation of the source before using it","Delete it from the file","Tell the borrower to say it was savings"],1,"Large unexplained deposits must be sourced and documented before they can be used as qualifying assets, since they may be undisclosed loans. Fabricating an explanation is fraud.","Agency asset guidelines; fraud prohibitions")
q(ETH,"5.2.4","Fluctuating income","medium","application-scenario","A self-employed borrower's income varies year to year. The ethical approach is to:",["Use only the best year","Analyze the income per program guidelines (e.g., averaging) using verified documentation","Use only the worst year to be safe","Estimate without documents"],1,"Variable self-employment income should be evaluated under program guidelines, typically averaging documented income over a representative period, using verified tax returns and financials, not cherry-picked or estimated figures.","Agency self-employment guidelines")
q(ETH,"5.1.6","Steering vs options","medium","application-scenario","To avoid steering, the LO compensation rule expects originators to:",["Always sell the highest-rate loan","Not receive compensation that varies with loan terms, so recommendations aren't skewed","Hide loan options","Recommend only ARMs"],1,"By barring compensation that varies with a transaction's terms, the rule removes the incentive to steer borrowers into worse loans, helping ensure recommendations reflect the borrower's interest.","Regulation Z, 12 CFR \u00a71026.36(d),(e)")
q(ETH,"5.2.2","Escalating complaints","medium","application-scenario","A borrower's complaint alleges a possible legal violation the MLO cannot resolve alone. The MLO should:",["Dismiss it","Escalate it through the company's compliance channels for proper handling","Delete the complaint","Tell the borrower nothing can be done"],1,"Complaints suggesting potential legal or compliance violations should be escalated through the company's compliance function for proper investigation and response, consistent with error-resolution obligations.","Regulation X error resolution; compliance practice")

# ---------- STATE (+2) ----------
q(STATE,"2.2.2","Consumer Access","easy","recall","NMLS Consumer Access allows the public to:",["Apply for loans","Verify an MLO's license status and identifier","Set interest rates","File taxes"],1,"NMLS Consumer Access is a free public website where consumers can look up an MLO or company by name or unique identifier to verify licensing status and history.","NMLS Consumer Access")
q(STATE,"2.3.11","Inactive license","medium","application-scenario","An MLO who lets their license lapse and later wants to originate again must generally:",["Do nothing","Reinstate or reapply and meet current CE and other requirements","Only pay a fee","Wait five years automatically"],1,"A lapsed or inactive license generally must be reinstated (within the allowed window) or reapplied for, satisfying current CE and other standards before the MLO may originate again.","NMLS renewal/reinstatement policy")

# ---- merge + re-id ----
data=json.load(open(os.path.join(HERE,"questions.json")))
order={FED:1,STATE:2,GEN:3,ORIG:4,ETH:5}
allq=data["questions"]+B
allq.sort(key=lambda x:(order[x["content_area"]],x["outline_ref"]))
for i,q_ in enumerate(allq,1): q_["id"]=f"Q{i:04d}"
data["questions"]=allq; data["meta"]["total"]=len(allq); data["meta"]["version"]="1.0"
json.dump(data,open(os.path.join(HERE,"questions.json"),"w"),indent=2,ensure_ascii=False)
print(f"Batch 3 added {len(B)} questions. New total: {len(allq)}")
